a= input('digite algo: ')
print(f'{a}O tipo primitivo desse valor é', type(a))
print(f'{a} só tem espaços?',a.isspace())
print(f'{a} é um numero?',a.isnumeric())
print(f'{a} é alfabetico?', a.isalpha())
print(f'{a} é Alfanumerico?', a.isalnum())
print(f'{a} Esta em maiusculas?', a.isupper())
print(f'{a} Esta em minusculas?', a.islower())
print(f'{a} Esta capitalizada?', a.istitle())
